language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before script:
  -psql -c "CREATE DATABASE test_db;" -U postgress

script:
  - python -m pytest --cov

after_success:
  - coveralls
